### ISSUE TITLE
SDXL support

### ISSUE THREAD

**Issue by khyinn** [chibiace/ComfyUI-Chibi-Nodes#1]
Hi :)
Really like your work, keep going !
Do you plan to add some specific nodes to support SDXL (CheckpointLoader with optional refiner, prompts encoder, etc.) ?

**Comment by chibiace** [comment]
Hello, Thanks.

I can look into it, but at the moment I only have a Nvidia 1070 and SDXL takes forever to make images so testing would be painful.

**Comment by chibiace** [comment]
Thinking to investigate more now that SDXL Turbo models are out, can actually generate pictures in a reasonable time with that.

**Comment by khyinn** [comment]
Good news 👍
