### ISSUE TITLE
Text input/output not real text input/output

### ISSUE THREAD

**Issue by Silvia-Rose** [chibiace/ComfyUI-Chibi-Nodes#2]
whenever I use your wildcard node I cannot input text from any other text/string nodes other than yours, same with the output.

**Comment by chibiace** [comment]
> whenever I use your wildcard node I cannot input text from any other text/string nodes other than yours, same with the output.

which nodes are you trying to use? I think it has something to do with mismatched names and I can have a go at fixing it. 

cheers.

**Comment by Silvia-Rose** [comment]
here are some examples

inputs it won't take:
- Text Multiline from WAS Node Suite
- Text from tinyterraNodes

Nodes it won't output to:
- Show Text 🐍 from pythongosssss/ComfyUI-Custom-Scripts
- textConcat from tinyterraNodes

**Comment by chibiace** [comment]
Alright, i uploaded what i hope to have fixed the issue, changed "TEXT" to "STRING",  i also added a simple textbox node.

also tinyterraNodes has a nice debug node too, thanks for letting me know about them.

**Comment by Silvia-Rose** [comment]
it works!, tysm! 💜

**Comment by Silvia-Rose** [comment]
Hey I really like your textbox node, but I have a suggestion to make it even better!

There's a bunch of other multiline textbox custom nodes in other suites like WAS Node Suite and Pythongosssss, but the one thing they're all missing is the ability to optionally receive a String input and pass that to the output while displaying the input on the multiline textbox (overwriting anything that might have been there).

That way you could both have a fixed text prompt and ALSO have it change dynamically based on the execution. All the existing nodes can only seem to do one or the other!

I just think that would be really useful, no pressure though :3

and again thank you for fixing the original issue !!

**Comment by chibiace** [comment]
that sounds good, I'll look into it when I get some free time

**Comment by chibiace** [comment]
> Hey I really like your textbox node, but I have a suggestion to make it even better!
> 
> There's a bunch of other multiline textbox custom nodes in other suites like WAS Node Suite and Pythongosssss, but the one thing they're all missing is the ability to optionally receive a String input and pass that to the output while displaying the input on the multiline textbox (overwriting anything that might have been there).
> 
> That way you could both have a fixed text prompt and ALSO have it change dynamically based on the execution. All the existing nodes can only seem to do one or the other!
> 
> I just think that would be really useful, no pressure though :3
> 
> and again thank you for fixing the original issue !!

i have uploaded an update to the textbox and done some general tweaks of stuff. let me know if this is what you were after and if there are any issues. 

cheers.

**Comment by Silvia-Rose** [comment]
Thank you so much !!, the textbox does exactly what I wanted !

I did however, find a bug with it:
when you change the text in the textbox and the passthrough is empty, it copies the value from the text into the passthrough, it's only supposed to copy passthrough to the text, this had me scratching my head until I turned "forceInput" on the passthrough to false for debugging and saw it happen, I managed to fix the issue entirely by making the following tweak~

```python  
def textbox(self,text="",passthrough=""):
        if passthrough != "":
            text = passthrough
            return {"ui": {"text": text},"result": (text,)}
        else:            
            return text,
```

again, Thank you _sooooo much_ for changing your textbox node like this, This makes it the most useful textbox node out there 💜

**Comment by chibiace** [comment]
probably my horrible coding lol
