### ISSUE TITLE
Example workflow please

### ISSUE THREAD

**Issue by shiloh92** [chibiace/ComfyUI-Chibi-Nodes#3]
I haven't been able to get this to work because I'm using efficiency nodes for setup in an array. Please add a workflow example that uses the wild cards!!!

**Comment by chibiace** [comment]
wildcard node replaces the keyword (by default` __wildcard__`) from inputted text
![Screenshot_20231121_165527](https://github.com/chibiace/ComfyUI-Chibi-Nodes/assets/21996875/5a572be0-af65-4bd2-aa22-1d5ea58e799d)

or if no inputted text is connected then it will output the wildcard by itself
![Screenshot_20231121_165756](https://github.com/chibiace/ComfyUI-Chibi-Nodes/assets/21996875/3b6a7bd3-6ed4-4439-8d56-dc774881989d)
