### ISSUE TITLE
Too confusing

### ISSUE THREAD

**Issue by shiloh92** [chibiace/ComfyUI-Chibi-Nodes#4]
I'm confused by this and wasn't able to get 4 wild cards to work. 
Can you clarify with a downloadable workflow that actually uses several wildcards effectively? 
I'm at odds and think there may be a more polished tool to get wildcards working easily, but this one seemed so close by all appearances to what I need.

**Comment by chibiace** [comment]
here you go:

[wildcards.json](https://github.com/chibiace/ComfyUI-Chibi-Nodes/files/13525411/wildcards.json)


![Screenshot_20231202_001030](https://github.com/chibiace/ComfyUI-Chibi-Nodes/assets/21996875/5debb498-bac5-43c5-bd16-aed229b26653)

**Comment by shiloh92** [comment]
Great! Thank you! I'd append it and label it clearly as Example Workflow. In case others have the same difficulty.
