### ISSUE TITLE
rename fonts -> chibi-fonts to avoid conflicts 

### ISSUE THREAD

**Issue by xingren23** [chibiace/ComfyUI-Chibi-Nodes#5]
ComfyUI-Chibi-Nodes and ComfyUI-Allor project both used folder_paths.folder_names_and_paths["fonts"]  path, there are conflicts between them. 

modify: 

folder_paths.folder_names_and_paths["chibi-wildcards"] = ([os.path.join(extras_dir, "chibi-wildcards")], {".txt"})
folder_paths.folder_names_and_paths["chibi-fonts"] = ([os.path.join(extras_dir, "chibi-fonts")], {".ttf"})

**Comment by chibiace** [comment]
got spotting, i suspected something like this might cause a problem. i'll get right on it.

**Comment by chibiace** [comment]
alright, give that a go. ive only assigned folder_paths.folder_names_and_paths["chibi-fonts"],  as the os.path.join part is just the subdirectory.

**Comment by xingren23** [comment]
thanks
