### ISSUE TITLE
LoadEmbedding node recognizes only the pt extension.

### ISSUE THREAD

**Issue by Neytiri7** [chibiace/ComfyUI-Chibi-Nodes#6]
The safetensors extension is not recognized, and an error occurs.
Error occurred when executing LoadEmbedding:

cannot identify image file 'O:\\AI\\SynologyDrive\\stable-diffusion-webui-SDXL\\embeddings\\A.safetensors'

File "O:\AI\SynologyDrive\ComfyUI-webui\ComfyUI\execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "O:\AI\SynologyDrive\ComfyUI-webui\ComfyUI\execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "O:\AI\SynologyDrive\ComfyUI-webui\ComfyUI\execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "O:\AI\SynologyDrive\ComfyUI-webui\ComfyUI\custom_nodes\ComfyUI-Chibi-Nodes\chibi_nodes.py", line 250, in loadembedding
image = Image.open(img_path)
^^^^^^^^^^^^^^^^^^^^
File "O:\AI\SynologyDrive\ComfyUI-webui\python_embeded\Lib\site-packages\PIL\Image.py", line 3298, in open
raise UnidentifiedImageError(msg)

**Comment by chibiace** [comment]
do textual inversion(embeddings) come in safetensor now? or is it a sdxl thing? thought they were all .pt

**Comment by Neytiri7** [comment]
Yes, we have an embedding in safetensors.

Maybe that's why the pt extension is normal, but the safetyensors extension is getting an error.
It's all confirmed in sd 1.5 and sdxl.

**Comment by Neytiri7** [comment]
https://civitai.com/models/100191/ti-easynegativev2-textual-inversion-embedding
https://civitai.com/models/118418/negativexl
This link is made of safetensors.

**Comment by chibiace** [comment]
ok, i think this has to do with the image preview i tried implementing on this node. i made a change. see how it goes. might need a rewrite at some point.
